// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PreparedStatementSpec defines the desired state of PreparedStatement.
//
// A prepared SQL statement for use with Athena.
type PreparedStatementSpec struct {

	// The description of the prepared statement.
	Description *string `json:"description,omitempty"`
	// The name of the prepared statement.
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The query string for the prepared statement.
	// +kubebuilder:validation:Required
	QueryStatement *string `json:"queryStatement"`
	// The name of the workgroup to which the prepared statement belongs.
	// +kubebuilder:validation:Required
	WorkGroup *string `json:"workGroup"`
}

// PreparedStatementStatus defines the observed state of PreparedStatement
type PreparedStatementStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
}

// PreparedStatement is the Schema for the PreparedStatements API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type PreparedStatement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              PreparedStatementSpec   `json:"spec,omitempty"`
	Status            PreparedStatementStatus `json:"status,omitempty"`
}

// PreparedStatementList contains a list of PreparedStatement
// +kubebuilder:object:root=true
type PreparedStatementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PreparedStatement `json:"items"`
}

func init() {
	SchemeBuilder.Register(&PreparedStatement{}, &PreparedStatementList{})
}
